version: '3'
services:
  backend:
    build: ./backend
    container_name: flask-api
    volumes:
      - ./backend:/app                 # Mount the backend code
      - ./backend/data:/app/data         # Mount volume for SQLite database persistence
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: ./backend
    container_name: celery-worker
    command: celery -A app.celery worker --loglevel=info -E
    depends_on:
      - redis
      - backend
    networks:
      - app-network

  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A app.celery beat --loglevel=info
    depends_on:
      - redis
      - backend
    networks:
      - app-network

        #frontend:
        #  build: ./frontend
        #  container_name: vuejs-frontend
        #  ports:
        #    - "8080:8080"
        #  depends_on:
        #    - backend
        #  networks:
        #    - app-network

networks:
  app-network:
    driver: bridge

